### YamlMime:ContentBrowser
title: Test Content Browser Page
browseType: learn
summary: |
    # Title
    *italic* 
    **bold** 
    ~~deleted~~ 
    [link](https://github.com)
metadata:
  title: Test metadata title
  description: Test metadata description
searchText: "Find content"
